# Generated by Django 4.2 on 2023-04-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sections',
            field=models.JSONField(null=True, verbose_name='Разделы задач'),
        ),
    ]
