# Generated by Django 4.2 on 2023-04-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Фамилия'),
        ),
    ]
