# Generated by Django 4.2 on 2023-05-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'ordering': ['time_complete']},
        ),
        migrations.AlterField(
            model_name='tasks',
            name='title',
            field=models.CharField(db_index=True, max_length=30, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.CharField(null=True, verbose_name='Фото'),
        ),
    ]
