# Generated by Django 4.2 on 2023-05-03 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sections',
            field=models.JSONField(default=None, null=True, verbose_name='Разделы задач'),
        ),
    ]
