# Generated by Django 4.2 on 2023-05-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_alter_user_sections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sections',
            field=models.JSONField(null=True, verbose_name='Разделы задач'),
        ),
    ]
