# Generated by Django 4.2 on 2023-05-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_alter_user_sections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(null=True, upload_to='userphoto', verbose_name='Фото'),
        ),
    ]
